#!/usr/bin/env python3
"""docat-index — regenerate docat/<status>/index.md from each issue's frontmatter.

Deterministic, stdlib-only, no dependencies. Safe no-op if there is no docat/ folder.
`updated` is derived from git (last commit date); never hand-written.

Usage: docat-index.py [repo_root]     (default: current directory)
"""
import os
import re
import subprocess
import sys

STATUSES = ["draft", "approved", "in-progress", "done"]


def parse_frontmatter(path):
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return {}
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        s = line.strip()
        if s and not s.startswith("#") and ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm


def git_updated(root, rel_path):
    try:
        out = subprocess.run(
            ["git", "-C", root, "log", "-1", "--format=%cs", "--", rel_path],
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "—"
    except Exception:
        return "—"


def gen_folder(root, status):
    folder = os.path.join(root, "docat", status)
    if not os.path.isdir(folder):
        return
    rows = []
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".md") or name == "index.md":
            continue
        fm = parse_frontmatter(os.path.join(folder, name))
        rows.append((
            fm.get("id", name[:-3]),
            fm.get("title", ""),
            fm.get("summary", ""),
            fm.get("assignee", ""),
            git_updated(root, f"docat/{status}/{name}"),
            name,
        ))
    lines = [
        "<!-- ⚙️ AUTO-GENERATED by docat-index — DO NOT EDIT (regenerated on commit/edit). -->",
        "",
        f"# {status} ({len(rows)})",
        "",
        "| id | title | summary | assignee | updated |",
        "|----|-------|---------|----------|---------|",
    ]
    for id_, title, summary, assignee, updated, fname in rows:
        lines.append(f"| [{id_}](./{fname}) | {title} | {summary} | {assignee} | {updated} |")
    lines.append("")
    with open(os.path.join(folder, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    if not os.path.isdir(os.path.join(root, "docat")):
        return 0  # no docat data here — no-op
    for status in STATUSES:
        gen_folder(root, status)
    return 0


if __name__ == "__main__":
    sys.exit(main())
