#!/usr/bin/env python3
"""waymark-index — regenerate waymark/<status>/index.md from each issue's frontmatter.

Deterministic, stdlib-only, no dependencies. Safe no-op if there is no waymark/ folder.
`created`/`updated` are derived from git (first/last commit dates); never hand-written.
`done/` dates are frozen, so they're reused from the existing index.md instead of
re-shelling git per doc — keeps commit time bounded as `done/` grows.

Usage: waymark-index.py [repo_root]     (default: current directory)
"""
import os
import re
import subprocess
import sys

STATUSES = ["draft", "approved", "in-progress", "done"]


def parse_frontmatter(path):
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return {}
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        s = line.strip()
        if s and not s.startswith("#") and ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm


def git_updated(root, rel_path):
    try:
        out = subprocess.run(
            ["git", "-C", root, "log", "-1", "--format=%cs", "--", rel_path],
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "—"
    except Exception:
        return "—"


def git_created(root, rel_path):
    # First commit date, following renames (files move between status folders via git mv).
    try:
        out = subprocess.run(
            ["git", "-C", root, "log", "--follow", "--format=%cs", "--", rel_path],
            capture_output=True, text=True, timeout=10,
        )
        dates = [d for d in out.stdout.splitlines() if d.strip()]
        return dates[-1] if dates else "—"
    except Exception:
        return "—"


def cell(v):
    # Escape table-breaking chars so a free-text value can't corrupt the markdown row.
    return str(v).replace("\n", " ").replace("|", "\\|").strip()


def load_done_cache(folder):
    # done/ is frozen → its created/updated never change. Reuse them from the existing
    # index.md instead of shelling out to git per doc, so commit time stays bounded as
    # done/ grows. New arrivals (not in the old index) fall through to a one-time git lookup.
    cache = {}
    try:
        with open(os.path.join(folder, "index.md"), encoding="utf-8") as f:
            for line in f:
                if not line.startswith("| ["):  # data rows only (skip header/separator)
                    continue
                cells = re.split(r"(?<!\\)\|", line.rstrip("\n"))  # split on UNescaped pipes
                if len(cells) < 4:
                    continue
                link = re.search(r"\]\(\./([^)]+)\)", cells[1])
                if link:
                    cache[link.group(1)] = (cells[-3].strip(), cells[-2].strip())
    except OSError:
        pass
    return cache


def gen_folder(root, status):
    folder = os.path.join(root, "waymark", status)
    if not os.path.isdir(folder):
        return
    cache = load_done_cache(folder) if status == "done" else {}
    rows = []
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".md") or name == "index.md":
            continue
        fm = parse_frontmatter(os.path.join(folder, name))
        rel = f"waymark/{status}/{name}"
        if name in cache:
            created, updated = cache[name]
        else:
            created = git_created(root, rel)
            updated = git_updated(root, rel)
        rows.append((
            fm.get("id", name[:-3]),
            fm.get("title", ""),
            fm.get("summary", ""),
            fm.get("assignee", ""),
            created,
            updated,
            name,
        ))
    lines = [
        "<!-- ⚙️ AUTO-GENERATED by waymark-index — DO NOT EDIT (regenerated on commit/edit). -->",
        "",
        f"# {status} ({len(rows)})",
        "",
        "| id | title | summary | assignee | created | updated |",
        "|----|-------|---------|----------|---------|---------|",
    ]
    for id_, title, summary, assignee, created, updated, fname in rows:
        lines.append(
            f"| [{cell(id_)}](./{fname}) | {cell(title)} | {cell(summary)} | "
            f"{cell(assignee)} | {created} | {updated} |"
        )
    lines.append("")
    with open(os.path.join(folder, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    if not os.path.isdir(os.path.join(root, "waymark")):
        return 0  # no waymark data here — no-op
    for status in STATUSES:
        gen_folder(root, status)
    return 0


if __name__ == "__main__":
    sys.exit(main())
